--
-- PostgreSQL database dump
--

\restrict aiqXAputkNh1zrXdq5cRm2MF2ELydLbnVm9f1u3IhNmmjugrDZWF6O3b7puFhLF

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: actualizar_stock_trigger(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.actualizar_stock_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE Productos
    SET stock_actual = stock_actual - NEW.cantidad
    WHERE id_producto = NEW.id_producto;

    RETURN NEW;
END;
$$;


--
-- Name: actualizar_total_venta_trigger(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.actualizar_total_venta_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE Ventas
    SET monto_total = (
        SELECT COALESCE(SUM(subtotal), 0)
        FROM Detalle_Venta
        WHERE id_venta = NEW.id_venta
    )
    WHERE id_venta = NEW.id_venta;

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cajas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cajas (
    diferencia numeric(38,2),
    id_caja integer NOT NULL,
    id_usuario integer NOT NULL,
    monto_inicial numeric(38,2) NOT NULL,
    monto_real numeric(38,2),
    monto_sistema numeric(38,2),
    fecha_apertura timestamp(6) without time zone NOT NULL,
    fecha_cierre timestamp(6) without time zone,
    estado character varying(20) NOT NULL
);


--
-- Name: cajas_id_caja_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cajas ALTER COLUMN id_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cajas_id_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    id_categoria_padre integer,
    codigo_corto character varying(10),
    nombre character varying(100) NOT NULL,
    descripcion character varying(255)
);


--
-- Name: categorias_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id_cliente integer NOT NULL,
    dni character varying(8) NOT NULL,
    fecha_registro timestamp(6) without time zone,
    celular character varying(9) NOT NULL,
    apellidos character varying(150) NOT NULL,
    nombres character varying(150) NOT NULL,
    email character varying(255)
);


--
-- Name: clientes_id_cliente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cupones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cupones (
    activo boolean NOT NULL,
    fecha_vencimiento date NOT NULL,
    hora_fin time(6) without time zone,
    hora_inicio time(6) without time zone,
    id_cupom integer NOT NULL,
    usos_disponibles integer NOT NULL,
    valor numeric(38,2) NOT NULL,
    codigo character varying(255) NOT NULL,
    dias_permitidos character varying(255),
    tipo_descuento character varying(255) NOT NULL,
    monto_minimo numeric(38,2)
);


--
-- Name: cupones_id_cupom_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cupones ALTER COLUMN id_cupom ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupones_id_cupom_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_venta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_venta (
    cantidad integer NOT NULL,
    id_detalle integer NOT NULL,
    id_producto integer NOT NULL,
    id_variante integer,
    id_venta integer,
    precio_unitario numeric(38,2) NOT NULL,
    subtotal numeric(38,2) NOT NULL
);


--
-- Name: detalle_venta_id_detalle_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_venta ALTER COLUMN id_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_venta_id_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imagenes_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imagenes_producto (
    id_imagen integer NOT NULL,
    id_producto integer,
    id_variante integer,
    orden integer,
    descripcion_alt character varying(255),
    url_imagen character varying(255) NOT NULL
);


--
-- Name: imagenes_producto_id_imagen_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imagenes_producto ALTER COLUMN id_imagen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagenes_producto_id_imagen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marcas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marcas (
    id_marca integer NOT NULL,
    codigo_corto character varying(10),
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);


--
-- Name: marcas_id_marca_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marcas ALTER COLUMN id_marca ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marcas_id_marca_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_variantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.producto_variantes (
    id_producto integer,
    id_variante integer NOT NULL,
    stock_actual integer NOT NULL,
    color character varying(50),
    talla character varying(50),
    sku_variante character varying(255),
    url_imagen character varying(255)
);


--
-- Name: producto_variantes_id_variante_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.producto_variantes ALTER COLUMN id_variante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_variantes_id_variante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos (
    id_categoria integer,
    id_marca integer,
    id_producto integer NOT NULL,
    precio_compra numeric(38,2),
    precio_regular numeric(38,2),
    precio_venta numeric(38,2) NOT NULL,
    stock_actual integer NOT NULL,
    codigo_sku character varying(255) NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL,
    url_imagen character varying(255),
    caracteristicas jsonb,
    CONSTRAINT productos_stock_actual_check CHECK ((stock_actual >= 0))
);


--
-- Name: productos_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    activo boolean,
    id_usuario integer NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    celular character varying(9),
    rol character varying(50) NOT NULL,
    nombre_usuario character varying(100) NOT NULL,
    apellidos character varying(150),
    nombres character varying(150),
    hash_contrasena character varying(255) NOT NULL,
    permisos jsonb
);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ventas (
    id_cliente integer,
    id_cupom integer,
    id_usuario integer NOT NULL,
    id_venta integer NOT NULL,
    monto_descuento numeric(38,2),
    total numeric(38,2) DEFAULT 0 NOT NULL,
    fecha_venta timestamp(6) without time zone,
    estado character varying(255),
    tipo_comprobante character varying(255) NOT NULL
);


--
-- Name: ventas_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ventas ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cajas; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cajas (diferencia, id_caja, id_usuario, monto_inicial, monto_real, monto_sistema, fecha_apertura, fecha_cierre, estado) FROM stdin;
\.


--
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.categorias (id_categoria, id_categoria_padre, codigo_corto, nombre, descripcion) FROM stdin;
1	\N	\N	Ropa
3	\N	\N	Calzado
4	\N	\N	Hogar
5	4	\N	Cortinas
6	4	\N	Protector de Muebles
7	4	\N	Forro de Mueble	Forro de Mueble
8	1	\N	Polo 	Polo
9	1	\N	Jean	Jean
10	1	\N	Casaca Jean	Casaca Jean
11	1	\N	Casaca	Casaca
12	1	\N	Polera	Polera
\.


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes (id_cliente, dni, fecha_registro, celular, apellidos, nombres, email) FROM stdin;
1	00000000	\N	999999999	General	Cliente	\N
\.


--
-- Data for Name: cupones; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cupones (activo, fecha_vencimiento, hora_fin, hora_inicio, id_cupom, usos_disponibles, valor, codigo, dias_permitidos, tipo_descuento, monto_minimo) FROM stdin;
t	2025-12-17	\N	\N	2	4	20.00	123456		FIJO	0.00
\.


--
-- Data for Name: detalle_venta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.detalle_venta (cantidad, id_detalle, id_producto, id_variante, id_venta, precio_unitario, subtotal) FROM stdin;
1	1	1	1	1	69.99	69.99
1	2	7	7	1	19.90	19.90
4	3	9	20	2	65.00	260.00
2	4	8	12	3	50.00	100.00
2	5	5	5	4	70.00	140.00
1	6	9	18	5	65.00	65.00
2	7	9	20	5	65.00	130.00
2	8	2	2	6	52.90	105.80
3	9	8	16	7	50.00	150.00
5	10	7	7	7	19.90	99.50
2	11	9	20	8	65.00	130.00
2	12	7	7	8	19.90	39.80
4	13	1	1	8	69.99	279.96
5	14	10	24	9	149.00	745.00
5	15	2	2	10	52.90	264.50
1	16	1	1	11	69.99	69.99
1	17	3	3	12	59.80	59.80
1	18	8	15	12	50.00	50.00
1	19	10	23	12	149.00	149.00
2	20	3	3	13	59.80	119.60
1	21	9	18	13	65.00	65.00
1	22	10	24	14	149.00	149.00
1	23	6	6	14	150.00	150.00
1	24	7	9	15	19.90	19.90
1	25	6	6	15	150.00	150.00
1	26	8	10	15	50.00	50.00
1	27	11	29	15	75.00	75.00
10	28	6	6	16	150.00	1500.00
10	29	7	8	16	19.90	199.00
3	30	7	9	16	19.90	59.70
1	31	7	7	16	19.90	19.90
1	32	6	6	17	150.00	150.00
\.


--
-- Data for Name: imagenes_producto; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.imagenes_producto (id_imagen, id_producto, id_variante, orden, descripcion_alt, url_imagen) FROM stdin;
61	3	3	0	Blackout 140x250 cm Grafito - Grafito	/media/403e031a-b8f4-45d8-8c4c-9f771d9f63f0_w=1500,h=1500,fit=pad (25).webp
62	3	3	0	Blackout 140x250 cm Grafito - Grafito	/media/1e0fc3d4-78d2-469d-b7ce-83e7751b183d_w=1500,h=1500,fit=pad (26).webp
63	3	3	0	Blackout 140x250 cm Grafito - Grafito	/media/25eb3157-29c8-471f-a8dd-67768d404f3c_w=1500,h=1500,fit=pad (27).webp
64	3	3	0	Blackout 140x250 cm Grafito - Grafito	/media/b1bc4e0a-9d69-4524-af95-7f6218a5dff2_w=1500,h=1500,fit=pad (28).webp
65	3	3	0	Blackout 140x250 cm Grafito - Grafito	/media/361bd8f1-2423-44c7-94de-efd09a6b08f0_w=1500,h=1500,fit=pad (29).webp
66	5	5	0	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris - Gris	/media/8e88b4f0-f4ef-4735-baa8-a253831c732c_w=1500,h=1500,fit=pad (30).webp
67	5	5	0	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris - Gris	/media/59af3dcc-fa89-4785-b4da-f2712a7b630e_w=1500,h=1500,fit=pad (31).webp
68	5	5	0	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris - Gris	/media/207cd8d5-d173-4942-aac6-bf839570e80e_w=1500,h=1500,fit=pad (32).webp
69	5	5	0	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris - Gris	/media/9b01ab6d-e487-424a-9895-a47ccfcf53e1_w=1500,h=1500,fit=pad (33).webp
70	5	5	0	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris - Gris	/media/074de99b-7d9a-4b9d-96ca-77240b1a9eaf_w=1500,h=1500,fit=pad (34).webp
71	6	6	0	Funda de mueble 3-2-1 labrado imperial - Negro - Negro	/media/253f4a51-304e-4b20-abb3-98ffe2607148_w=1500,h=1500,fit=pad (35).webp
72	6	6	0	Funda de mueble 3-2-1 labrado imperial - Negro - Negro	/media/5ab7e08e-cd2d-4af3-897d-3762de9ad092_w=1500,h=1500,fit=pad (36).webp
73	6	6	0	Funda de mueble 3-2-1 labrado imperial - Negro - Negro	/media/488fd73a-9dae-4a88-aee3-6abf1d23fa57_w=1500,h=1500,fit=pad (37).webp
74	7	7	0	Polo Oversize Hombre Algodon Color Beige - Beige	/media/9f025cdd-f005-437e-af5d-014a61d9b870_w=1500,h=1500,fit=pad (38).webp
75	7	8	0	Polo Oversize Hombre Algodon Color Beige - Beige	/media/26d4b6fa-8e5b-4d2d-944c-776710df49b1_w=1500,h=1500,fit=pad (39).webp
76	7	9	0	Polo Oversize Hombre Algodon Color Beige - Beige	/media/67b41d86-d121-4325-922e-634b3967cf3a_w=1500,h=1500,fit=pad (40).webp
239	8	12	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
240	8	12	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b048fb8e-e8e4-4f2a-8142-d6f0edff6945_w=1500,h=1500,fit=pad (42).webp
241	8	12	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b6a25f88-95d4-4db5-9cf1-27ccb15f3b4b_w=1500,h=1500,fit=pad (41).webp
242	8	10	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
243	8	10	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b048fb8e-e8e4-4f2a-8142-d6f0edff6945_w=1500,h=1500,fit=pad (42).webp
244	8	10	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b6a25f88-95d4-4db5-9cf1-27ccb15f3b4b_w=1500,h=1500,fit=pad (41).webp
245	8	11	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
246	8	11	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b048fb8e-e8e4-4f2a-8142-d6f0edff6945_w=1500,h=1500,fit=pad (42).webp
247	8	11	0	Jean Algodón Baggy Fit Hombre Bearcliff - Negro	/media/b6a25f88-95d4-4db5-9cf1-27ccb15f3b4b_w=1500,h=1500,fit=pad (41).webp
86	9	18	0	CASACAS JEANS MODA CASUAL ELEGANTE - Blanco	/media/f0fe83d4-5433-431a-b27d-de39d9f1bc6b_w=1500,h=1500,fit=pad (50).webp
87	9	18	0	CASACAS JEANS MODA CASUAL ELEGANTE - Blanco	/media/6b2cc76e-b129-4a1b-ad4a-b251209df881_w=1500,h=1500,fit=pad (51).webp
88	9	18	0	CASACAS JEANS MODA CASUAL ELEGANTE - Blanco	/media/4197dcd4-af4c-4e39-b9bd-54bfdd99e4cc_w=1500,h=1500,fit=pad (52).webp
89	10	21	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	/media/52eae3ba-3bf0-4235-a8ff-8a454c22c313_w=1500,h=1500,fit=pad (53).webp
90	10	21	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	/media/fcebdca3-05c1-4c11-929d-b77f00d45976_w=1500,h=1500,fit=pad (54).webp
91	10	22	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	/media/24e256e1-d99a-44a6-bfe1-d902514d8d46_w=1500,h=1500,fit=pad (55).webp
92	10	23	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	/media/d2020842-167e-4d28-8374-f185e1df1536_w=1500,h=1500,fit=pad (56).webp
93	10	24	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	/media/0607d4dd-abff-4431-b220-c0058de94aa7_w=1500,h=1500,fit=pad (57).webp
94	1	1	0	Cortina Blackout Textura 200x220cm Arena - Arena	/media/eab94c57-7c47-437a-9ed1-abe523af9493_w=1500,h=1500,fit=pad (15).webp
95	1	1	0	Cortina Blackout Textura 200x220cm Arena - Arena	/media/375b09b6-36f6-4ce9-85ef-c6c70d9b63eb_w=1500,h=1500,fit=pad (16).webp
96	1	1	0	Cortina Blackout Textura 200x220cm Arena - Arena	/media/36c0e6b2-90cb-4726-892f-85c52267dee3_w=1500,h=1500,fit=pad (17).webp
248	8	16	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
249	8	16	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/30f30f2d-799b-4cf6-8d4b-c4385a14ff19_w=1500,h=1500,fit=pad (47).webp
250	8	16	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/ee90c533-099f-4180-8666-b49e67a84e15_w=1500,h=1500,fit=pad (46).webp
251	8	16	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/d2fde878-779c-4801-a10d-5ce350979f1a_w=1500,h=1500,fit=pad (48).webp
252	8	15	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
97	1	1	0	Cortina Blackout Textura 200x220cm Arena - Arena	/media/9fe9330b-96fa-4fff-b46e-c8abfaf5a853_w=1500,h=1500,fit=pad (18).webp
98	1	1	0	Cortina Blackout Textura 200x220cm Arena - Arena	/media/e41c0982-d67d-4c5b-8e48-f80c3b598eae_w=1500,h=1500,fit=pad (19).webp
253	8	15	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/30f30f2d-799b-4cf6-8d4b-c4385a14ff19_w=1500,h=1500,fit=pad (47).webp
254	8	15	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/ee90c533-099f-4180-8666-b49e67a84e15_w=1500,h=1500,fit=pad (46).webp
255	8	15	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/d2fde878-779c-4801-a10d-5ce350979f1a_w=1500,h=1500,fit=pad (48).webp
256	8	17	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
257	8	17	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/30f30f2d-799b-4cf6-8d4b-c4385a14ff19_w=1500,h=1500,fit=pad (47).webp
258	8	17	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/ee90c533-099f-4180-8666-b49e67a84e15_w=1500,h=1500,fit=pad (46).webp
259	8	17	0	Jean Algodón Baggy Fit Hombre Bearcliff - Azul	/media/d2fde878-779c-4801-a10d-5ce350979f1a_w=1500,h=1500,fit=pad (48).webp
260	8	13	0	Jean Algodón Baggy Fit Hombre Bearcliff - Celeste	/media/84518197-f910-41dc-b88e-7b6a98647cc9_w=1500,h=1500,fit=pad (45).webp
261	8	13	0	Jean Algodón Baggy Fit Hombre Bearcliff - Celeste	/media/3b1d3db7-d648-45c0-9151-fffc4fc0c35b_w=1500,h=1500,fit=pad (44).webp
262	8	14	0	Jean Algodón Baggy Fit Hombre Bearcliff - Celeste	/media/84518197-f910-41dc-b88e-7b6a98647cc9_w=1500,h=1500,fit=pad (45).webp
263	8	14	0	Jean Algodón Baggy Fit Hombre Bearcliff - Celeste	/media/3b1d3db7-d648-45c0-9151-fffc4fc0c35b_w=1500,h=1500,fit=pad (44).webp
264	2	2	0	Cortina Blackout Textura 140x220cm Gris - Gris	/media/60c6fb0d-d489-4db6-a9e3-ef28b9506732_w=1500,h=1500,fit=pad (20).webp
265	2	2	0	Cortina Blackout Textura 140x220cm Gris - Gris	/media/604698a5-9f45-40a2-bb0c-7ad3c21f2152_w=1500,h=1500,fit=pad (21).webp
266	2	2	0	Cortina Blackout Textura 140x220cm Gris - Gris	/media/f717f963-3f33-471b-9438-decba440c015_w=1500,h=1500,fit=pad (22).webp
267	2	2	0	Cortina Blackout Textura 140x220cm Gris - Gris	/media/2442e179-807c-4966-8ff6-724f0bc39702_w=1500,h=1500,fit=pad (23).webp
268	2	2	0	Cortina Blackout Textura 140x220cm Gris - Gris	/media/b249aca3-491f-471f-8264-ae8f754aa186_w=1500,h=1500,fit=pad (24).webp
269	11	25	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
270	11	25	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/8fbbec14-c744-40f7-9e69-72e4b2e814ab_w=1500,h=1500,fit=pad (59).webp
271	11	26	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
272	11	26	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/8fbbec14-c744-40f7-9e69-72e4b2e814ab_w=1500,h=1500,fit=pad (59).webp
273	11	27	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
274	11	27	0	Polera Hombre Yansus Estampado Romantic - Rosa	/media/8fbbec14-c744-40f7-9e69-72e4b2e814ab_w=1500,h=1500,fit=pad (59).webp
275	11	28	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
276	11	28	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/02de14a6-b26c-4e10-bb57-59e6513b995d_w=1500,h=1500,fit=pad (61).webp
277	11	29	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
278	11	29	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/02de14a6-b26c-4e10-bb57-59e6513b995d_w=1500,h=1500,fit=pad (61).webp
279	11	30	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
280	11	30	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/02de14a6-b26c-4e10-bb57-59e6513b995d_w=1500,h=1500,fit=pad (61).webp
281	11	31	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
282	11	31	0	Polera Hombre Yansus Estampado Romantic - Blanco	/media/02de14a6-b26c-4e10-bb57-59e6513b995d_w=1500,h=1500,fit=pad (61).webp
\.


--
-- Data for Name: marcas; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.marcas (id_marca, codigo_corto, descripcion, nombre) FROM stdin;
1	\N	JUST HOME COLLECTION	JUST HOME COLLECTION
2	\N	EVERSO	EVERSO
3	\N	SALA FABULOSA	SALA FABULOSA
4	\N	HOLGU	HOLGU
5	\N	BEARCLIFF	BEARCLIFF
6	\N	Krainet	Krainet
7	\N		Adidas
8	\N	YANSUS	YANSUS
\.


--
-- Data for Name: producto_variantes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.producto_variantes (id_producto, id_variante, stock_actual, color, talla, sku_variante, url_imagen) FROM stdin;
11	31	12	Blanco	XXL	\N	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
10	24	4	Negro	XL		/media/0607d4dd-abff-4431-b220-c0058de94aa7_w=1500,h=1500,fit=pad (57).webp
9	19	8	Blanco	M
10	21	12	Negro	S		/media/52eae3ba-3bf0-4235-a8ff-8a454c22c313_w=1500,h=1500,fit=pad (53).webp
10	22	10	Negro	M		/media/24e256e1-d99a-44a6-bfe1-d902514d8d46_w=1500,h=1500,fit=pad (55).webp
8	10	11	Negro	28	\N	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
5	5	10	Gris	3pzs		/media/8e88b4f0-f4ef-4735-baa8-a253831c732c_w=1500,h=1500,fit=pad (30).webp
11	29	9	Blanco	M	\N	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
9	20	4	Blanco	L
7	8	14	Beige	M		/media/26d4b6fa-8e5b-4d2d-944c-776710df49b1_w=1500,h=1500,fit=pad (39).webp
7	9	7	Beige	L		/media/67b41d86-d121-4325-922e-634b3967cf3a_w=1500,h=1500,fit=pad (40).webp
7	7	4	Beige	S		/media/9f025cdd-f005-437e-af5d-014a61d9b870_w=1500,h=1500,fit=pad (38).webp
8	12	10	Negro	32	\N	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
1	1	20	Arena	200cmx220cm		/media/eab94c57-7c47-437a-9ed1-abe523af9493_w=1500,h=1500,fit=pad (15).webp
6	6	14	Negro	3pzs		/media/253f4a51-304e-4b20-abb3-98ffe2607148_w=1500,h=1500,fit=pad (35).webp
8	11	12	Negro	30	\N	/media/ffdbe00f-4bb2-4b8c-a2b2-e5f272bf47c1_w=1500,h=1500,fit=pad (43).webp
8	16	9	Azul	32	\N	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
8	17	9	Azul	36	\N	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
8	13	7	Celeste	30	\N	/media/84518197-f910-41dc-b88e-7b6a98647cc9_w=1500,h=1500,fit=pad (45).webp
8	14	10	Celeste	32	\N	/media/84518197-f910-41dc-b88e-7b6a98647cc9_w=1500,h=1500,fit=pad (45).webp
8	15	7	Azul	30	\N	/media/27a06290-c4fd-4113-8161-5bee4e18cc40_w=1500,h=1500,fit=pad (49).webp
10	23	7	Negro	L		/media/d2020842-167e-4d28-8374-f185e1df1536_w=1500,h=1500,fit=pad (56).webp
3	3	12	Grafito	140cmx250cm		/media/403e031a-b8f4-45d8-8c4c-9f771d9f63f0_w=1500,h=1500,fit=pad (25).webp
9	18	3	Blanco	S		/media/f0fe83d4-5433-431a-b27d-de39d9f1bc6b_w=1500,h=1500,fit=pad (50).webp
2	2	20	Gris	140cmx220cm	\N	/media/60c6fb0d-d489-4db6-a9e3-ef28b9506732_w=1500,h=1500,fit=pad (20).webp
11	25	12	Rosa	S	\N	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
11	26	15	Rosa	M	\N	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
11	27	19	Rosa	L	\N	/media/c3b36f9f-046e-4c2d-93d5-cde346ad8f73_w=1500,h=1500,fit=pad (58).webp
11	28	19	Blanco	S	\N	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
11	30	9	Blanco	L	\N	/media/8933607d-5cdf-41f9-9371-89179242f163_w=1500,h=1500,fit=pad (60).webp
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos (id_categoria, id_marca, id_producto, precio_compra, precio_regular, precio_venta, stock_actual, codigo_sku, descripcion, nombre, url_imagen, caracteristicas) FROM stdin;
5	1	2	30.00	90.00	52.90	20	COR-JUS-002	Cortina Blackout Textura 140x220cm Gris	Cortina Blackout Textura 140x220cm Gris		{}
11	7	10	70.00	200.00	149.00	33	CAS-ADI-001	Casaca Training Hombre Adidas D4t Full-zip	Casaca Training Hombre Adidas D4t Full-zip		{}
6	2	5	25.00	90.00	70.00	10	PRO-EVE-001	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris	Fundascubre Sofa Sillon2 Plazas Para Mascotas Reversible Gris		{}
9	5	8	40.00	80.00	50.00	75	JEA-BEA-001	Jean Algodón Baggy Fit Hombre Bearcliff	Jean Algodón Baggy Fit Hombre Bearcliff		{}
12	8	11	45.00	90.00	75.00	95	POL-YAN-001	Polera Hombre Yansus Estampado Romantic	Polera Hombre Yansus Estampado Romantic		{}
8	4	7	10.00	40.00	19.90	25	POL-HOL-001	Polo Oversize Hombre Algodon Color Beige	Polo Oversize Hombre Algodon Color Beige		{}
5	1	1	30.00	90.00	69.99	20	COR-JUS-001	Cortina Blackout Textura 200x220cm Arena	Cortina Blackout Textura 200x220cm Arena		{"tela": "seda", "corte": "Recto"}
7	3	6	100.00	190.00	150.00	14	FOR-SAL-001	Funda de mueble 3-2-1 labrado imperial - Negro	Funda de mueble 3-2-1 labrado imperial - Negro		{}
5	1	3	30.00	70.00	59.80	12	COR-JUS-003	Blackout 140x250 cm Grafito	Blackout 140x250 cm Grafito		{"tela": "algodon", "corte": "Recto"}
10	6	9	45.00	70.00	65.00	15	CAS-KRA-001	CASACAS JEANS MODA CASUAL ELEGANTE	CASACAS JEANS MODA CASUAL ELEGANTE		{}
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios (activo, id_usuario, fecha_creacion, celular, rol, nombre_usuario, apellidos, nombres, hash_contrasena, permisos) FROM stdin;
t	2	2025-12-15 22:18:24.253725	999999999	ADMIN	admin	Admin	Super	$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG	\N
t	3	\N	900944156	ADMIN	hugomeneses	Meneses Inca	Hugo Mishell	$2a$10$BNxzxkoLKrKnGik5TRiEXey54uW.Jy3.T29ldCyC6xd6tbXpnh23y	[]
t	4	\N	945641651	VENDEDOR	bubuchita	Alcala Peralta	Angie Nicole	$2a$10$DNz6lb5H3MTIAvQshX6WY.bw88RCoGPsmJeVsB.A3B0fkBUzJ6iIG	[]
t	5	\N	989784785	VENDEDOR	maga	Maga Maga	Maga	$2a$10$v7C5wv1EtkQAc3djXf9VPOnH1rRh9p5H5mrNawM8vDb9wtdnos3wC	[]
t	6	\N	948464131	VENDEDOR	esmeralda	EsmeraldaEsmeralda	Esmeralda	$2a$10$ZYigoPXTZ0GOv6yAi.riaOs2tpwwJTfpcY1y7MvBgbd//og6mIUfe	[]
t	7	\N	971726362	VENDEDOR	carlospro	Meneses Inca	Juan Carlos	$2a$10$FKGC/RRbDkUMRyfXbaL5he1B7OIjuomNpQmWEf4wpB2OKuJYaUeZu	[]
\.


--
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ventas (id_cliente, id_cupom, id_usuario, id_venta, monto_descuento, total, fecha_venta, estado, tipo_comprobante) FROM stdin;
1	\N	5	1	0.00	89.89	2025-12-16 22:15:39.924028	COMPLETADA	boleta
1	2	4	2	20.00	240.00	2025-12-16 18:31:24.772817	COMPLETADA	boleta
1	2	5	3	20.00	80.00	2025-12-16 19:57:26.398233	COMPLETADA	boleta
1	\N	5	4	0.00	140.00	2025-12-16 19:58:16.123297	COMPLETADA	boleta
1	\N	5	5	0.00	195.00	2025-12-16 20:00:26.619429	COMPLETADA	boleta
1	2	6	6	20.00	85.80	2025-12-16 20:06:40.15954	COMPLETADA	boleta
1	2	6	7	20.00	229.50	2025-12-16 20:08:33.682674	COMPLETADA	boleta
1	2	7	8	20.00	429.76	2025-12-16 20:17:22.755706	COMPLETADA	boleta
1	\N	7	9	0.00	745.00	2025-12-16 20:18:54.06197	ANULADA	boleta
1	2	7	10	20.00	244.50	2025-12-16 20:20:37.246129	ANULADA	boleta
1	\N	5	11	0.00	69.99	2025-12-16 21:49:23.771586	COMPLETADA	boleta
1	\N	4	12	0.00	258.80	2025-12-19 20:02:15.458792	COMPLETADA	boleta
1	\N	4	13	0.00	184.60	2025-12-19 23:14:35.719588	COMPLETADA	boleta
1	\N	4	14	0.00	299.00	2025-12-19 23:27:40.873408	COMPLETADA	boleta
1	\N	4	15	0.00	294.90	2025-12-19 23:34:58.287013	COMPLETADA	boleta
1	\N	4	16	0.00	1778.60	2025-12-23 13:17:52.449014	ANULADA	boleta
1	\N	4	17	0.00	150.00	2025-12-23 13:59:32.967953	COMPLETADA	boleta
\.


--
-- Name: cajas_id_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cajas_id_caja_seq', 1, false);


--
-- Name: categorias_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categorias_id_categoria_seq', 12, true);


--
-- Name: clientes_id_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clientes_id_cliente_seq', 1, true);


--
-- Name: cupones_id_cupom_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cupones_id_cupom_seq', 2, true);


--
-- Name: detalle_venta_id_detalle_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.detalle_venta_id_detalle_seq', 32, true);


--
-- Name: imagenes_producto_id_imagen_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.imagenes_producto_id_imagen_seq', 282, true);


--
-- Name: marcas_id_marca_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.marcas_id_marca_seq', 8, true);


--
-- Name: producto_variantes_id_variante_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.producto_variantes_id_variante_seq', 31, true);


--
-- Name: productos_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_id_producto_seq', 11, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 7, true);


--
-- Name: ventas_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ventas_id_venta_seq', 17, true);


--
-- Name: cajas cajas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cajas
    ADD CONSTRAINT cajas_pkey PRIMARY KEY (id_caja);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria);


--
-- Name: clientes clientes_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_dni_key UNIQUE (dni);


--
-- Name: clientes clientes_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_email_key UNIQUE (email);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente);


--
-- Name: cupones cupones_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT cupones_codigo_key UNIQUE (codigo);


--
-- Name: cupones cupones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT cupones_pkey PRIMARY KEY (id_cupom);


--
-- Name: detalle_venta detalle_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT detalle_venta_pkey PRIMARY KEY (id_detalle);


--
-- Name: imagenes_producto imagenes_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT imagenes_producto_pkey PRIMARY KEY (id_imagen);


--
-- Name: marcas marcas_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_nombre_key UNIQUE (nombre);


--
-- Name: marcas marcas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_pkey PRIMARY KEY (id_marca);


--
-- Name: producto_variantes producto_variantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto_variantes
    ADD CONSTRAINT producto_variantes_pkey PRIMARY KEY (id_variante);


--
-- Name: productos productos_codigo_sku_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_codigo_sku_key UNIQUE (codigo_sku);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id_producto);


--
-- Name: usuarios usuarios_nombre_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_nombre_usuario_key UNIQUE (nombre_usuario);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id_venta);


--
-- Name: detalle_venta fk2ens3kcdecgap5og51rbsp1h0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fk2ens3kcdecgap5og51rbsp1h0 FOREIGN KEY (id_variante) REFERENCES public.producto_variantes(id_variante);


--
-- Name: imagenes_producto fk9bgwqaobnsa1muydxwo18en5r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT fk9bgwqaobnsa1muydxwo18en5r FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: ventas fk9mbivrllsn9jffa05x77l5mc1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk9mbivrllsn9jffa05x77l5mc1 FOREIGN KEY (id_cupom) REFERENCES public.cupones(id_cupom);


--
-- Name: categorias fkbt5pdc52jh54l2o97ic983j26; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT fkbt5pdc52jh54l2o97ic983j26 FOREIGN KEY (id_categoria_padre) REFERENCES public.categorias(id_categoria);


--
-- Name: productos fkc1mrc7r89nch4xtol227kdwce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkc1mrc7r89nch4xtol227kdwce FOREIGN KEY (id_marca) REFERENCES public.marcas(id_marca);


--
-- Name: productos fkdtoa37luoxhhvbicrfiu5ygbj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkdtoa37luoxhhvbicrfiu5ygbj FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria);


--
-- Name: detalle_venta fke92fd2auy9ms2pvac9b4n8ttq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fke92fd2auy9ms2pvac9b4n8ttq FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: detalle_venta fkgds50vmwbs8lxoti80iekstyi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fkgds50vmwbs8lxoti80iekstyi FOREIGN KEY (id_venta) REFERENCES public.ventas(id_venta);


--
-- Name: cajas fkkal46lhycb4457wk2b7r9gb80; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cajas
    ADD CONSTRAINT fkkal46lhycb4457wk2b7r9gb80 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: ventas fkleerof1mym3gc1ah8hsarel3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkleerof1mym3gc1ah8hsarel3f FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente);


--
-- Name: imagenes_producto fkmlw1jk3iwkgb04aea290rp09x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT fkmlw1jk3iwkgb04aea290rp09x FOREIGN KEY (id_variante) REFERENCES public.producto_variantes(id_variante);


--
-- Name: ventas fkngvsjlvvv240ohesoj9e87s3h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkngvsjlvvv240ohesoj9e87s3h FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: producto_variantes fkq7ega29yp2m3irjvvrfrwsq6i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto_variantes
    ADD CONSTRAINT fkq7ega29yp2m3irjvvrfrwsq6i FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- PostgreSQL database dump complete
--

\unrestrict aiqXAputkNh1zrXdq5cRm2MF2ELydLbnVm9f1u3IhNmmjugrDZWF6O3b7puFhLF

