--
-- PostgreSQL database dump
--

\restrict lZEOxUGJJXU2fUDJJrZlS5UggAwJIvCt82heAydaeydDUfDJNOgC3gRewABTpYz

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg12+2)
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: margarita_db_v2_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO margarita_db_v2_user;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: margarita_db_v2_user
--

COMMENT ON SCHEMA public IS '';


--
-- Name: actualizar_stock_trigger(); Type: FUNCTION; Schema: public; Owner: margarita_db_v2_user
--

CREATE FUNCTION public.actualizar_stock_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE Productos
    SET stock_actual = stock_actual - NEW.cantidad
    WHERE id_producto = NEW.id_producto;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.actualizar_stock_trigger() OWNER TO margarita_db_v2_user;

--
-- Name: actualizar_total_venta_trigger(); Type: FUNCTION; Schema: public; Owner: margarita_db_v2_user
--

CREATE FUNCTION public.actualizar_total_venta_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE Ventas
    SET monto_total = (
        SELECT COALESCE(SUM(subtotal), 0)
        FROM Detalle_Venta
        WHERE id_venta = NEW.id_venta
    )
    WHERE id_venta = NEW.id_venta;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.actualizar_total_venta_trigger() OWNER TO margarita_db_v2_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cajas; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.cajas (
    diferencia numeric(38,2),
    id_caja integer NOT NULL,
    id_usuario integer NOT NULL,
    monto_inicial numeric(38,2) NOT NULL,
    monto_real numeric(38,2),
    monto_sistema numeric(38,2),
    fecha_apertura timestamp(6) without time zone NOT NULL,
    fecha_cierre timestamp(6) without time zone,
    estado character varying(20) NOT NULL
);


ALTER TABLE public.cajas OWNER TO margarita_db_v2_user;

--
-- Name: cajas_id_caja_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.cajas ALTER COLUMN id_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cajas_id_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    id_categoria_padre integer,
    codigo_corto character varying(10),
    nombre character varying(100) NOT NULL,
    descripcion character varying(255)
);


ALTER TABLE public.categorias OWNER TO margarita_db_v2_user;

--
-- Name: categorias_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.clientes (
    id_cliente integer NOT NULL,
    dni character varying(8),
    fecha_registro timestamp(6) without time zone,
    celular character varying(9) NOT NULL,
    apellidos character varying(150) NOT NULL,
    nombres character varying(150) NOT NULL,
    email character varying(255)
);


ALTER TABLE public.clientes OWNER TO margarita_db_v2_user;

--
-- Name: clientes_id_cliente_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.clientes ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cupones; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.cupones (
    activo boolean NOT NULL,
    fecha_vencimiento date NOT NULL,
    hora_fin time(6) without time zone,
    hora_inicio time(6) without time zone,
    id_cupom integer NOT NULL,
    usos_disponibles integer NOT NULL,
    valor numeric(38,2) NOT NULL,
    codigo character varying(255) NOT NULL,
    dias_permitidos character varying(255),
    tipo_descuento character varying(255) NOT NULL,
    monto_minimo numeric(38,2)
);


ALTER TABLE public.cupones OWNER TO margarita_db_v2_user;

--
-- Name: cupones_id_cupom_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.cupones ALTER COLUMN id_cupom ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupones_id_cupom_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_venta; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.detalle_venta (
    cantidad integer NOT NULL,
    id_detalle integer NOT NULL,
    id_producto integer NOT NULL,
    id_variante integer,
    id_venta integer,
    precio_unitario numeric(38,2) NOT NULL,
    subtotal numeric(38,2) NOT NULL
);


ALTER TABLE public.detalle_venta OWNER TO margarita_db_v2_user;

--
-- Name: detalle_venta_id_detalle_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.detalle_venta ALTER COLUMN id_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_venta_id_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imagenes_producto; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.imagenes_producto (
    id_imagen integer NOT NULL,
    id_producto integer,
    id_variante integer,
    orden integer,
    descripcion_alt character varying(255),
    url_imagen character varying(255) NOT NULL
);


ALTER TABLE public.imagenes_producto OWNER TO margarita_db_v2_user;

--
-- Name: imagenes_producto_id_imagen_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.imagenes_producto ALTER COLUMN id_imagen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagenes_producto_id_imagen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marcas; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.marcas (
    id_marca integer NOT NULL,
    codigo_corto character varying(10),
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.marcas OWNER TO margarita_db_v2_user;

--
-- Name: marcas_id_marca_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.marcas ALTER COLUMN id_marca ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marcas_id_marca_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.movimientos (
    id_movimiento integer NOT NULL,
    comentario character varying(255),
    comprobante character varying(255),
    fecha timestamp(6) without time zone NOT NULL,
    monto double precision NOT NULL,
    tipo character varying(255) NOT NULL,
    id_cliente integer NOT NULL
);


ALTER TABLE public.movimientos OWNER TO margarita_db_v2_user;

--
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.movimientos ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_variantes; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.producto_variantes (
    id_producto integer,
    id_variante integer NOT NULL,
    stock_actual integer NOT NULL,
    color character varying(50),
    talla character varying(50),
    sku_variante character varying(255),
    url_imagen character varying(255)
);


ALTER TABLE public.producto_variantes OWNER TO margarita_db_v2_user;

--
-- Name: producto_variantes_id_variante_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.producto_variantes ALTER COLUMN id_variante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_variantes_id_variante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.productos (
    id_categoria integer,
    id_marca integer,
    id_producto integer NOT NULL,
    precio_compra numeric(38,2),
    precio_regular numeric(38,2),
    precio_venta numeric(38,2) NOT NULL,
    stock_actual integer NOT NULL,
    codigo_sku character varying(255) NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL,
    url_imagen character varying(255),
    caracteristicas jsonb,
    en_oferta boolean DEFAULT false,
    CONSTRAINT productos_stock_actual_check CHECK ((stock_actual >= 0))
);


ALTER TABLE public.productos OWNER TO margarita_db_v2_user;

--
-- Name: productos_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.productos ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.usuarios (
    activo boolean,
    id_usuario integer NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    celular character varying(9),
    rol character varying(50) NOT NULL,
    nombre_usuario character varying(100) NOT NULL,
    apellidos character varying(150),
    nombres character varying(150),
    hash_contrasena character varying(255) NOT NULL,
    permisos jsonb
);


ALTER TABLE public.usuarios OWNER TO margarita_db_v2_user;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas; Type: TABLE; Schema: public; Owner: margarita_db_v2_user
--

CREATE TABLE public.ventas (
    id_cliente integer,
    id_cupom integer,
    id_usuario integer NOT NULL,
    id_venta integer NOT NULL,
    monto_descuento numeric(38,2),
    total numeric(38,2) DEFAULT 0 NOT NULL,
    fecha_venta timestamp(6) without time zone,
    estado character varying(255),
    tipo_comprobante character varying(255) NOT NULL
);


ALTER TABLE public.ventas OWNER TO margarita_db_v2_user;

--
-- Name: ventas_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE public.ventas ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cajas; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.cajas (diferencia, id_caja, id_usuario, monto_inicial, monto_real, monto_sistema, fecha_apertura, fecha_cierre, estado) FROM stdin;
\.


--
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.categorias (id_categoria, id_categoria_padre, codigo_corto, nombre, descripcion) FROM stdin;
7	\N	\N	Ropa	
8	\N	\N	Calzado	
9	\N	\N	Hogar	
10	\N	\N	Accesorios	
11	7	\N	Polo	
12	7	\N	Pantalon	
13	8	\N	Sandalias	
14	7	\N	Casaca	
\.


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.clientes (id_cliente, dni, fecha_registro, celular, apellidos, nombres, email) FROM stdin;
1	76225239	\N	900944156	Meneses Inca	Hugo	
2	12131231	\N	985845365	Inca	Ali	zerolein19@gmail.com
4	14516165	\N	988946146	gerardogerardo	gerardo	az64@gmail.com
8	77777777	\N	999999999	Oscar Oscar	Oscar Oscar	Oscar@asdsa
9	00000000	\N	999999999	General	Cliente	\N
15	42121212	\N	996363232	Meneses Inca	Carlos juan	carlos@gmail.com
17	45421231	\N	985145151	alonmso alonmso	alonmso	\N
18	\N	\N	978454131	asdsafsasdsafs	asdsafs	\N
11	\N	\N	984546161	FerFer	Fer	\N
19	\N	\N	972123132	rerefrr	rreeffe	\N
\.


--
-- Data for Name: cupones; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.cupones (activo, fecha_vencimiento, hora_fin, hora_inicio, id_cupom, usos_disponibles, valor, codigo, dias_permitidos, tipo_descuento, monto_minimo) FROM stdin;
\.


--
-- Data for Name: detalle_venta; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.detalle_venta (cantidad, id_detalle, id_producto, id_variante, id_venta, precio_unitario, subtotal) FROM stdin;
1	1	4	16	1	190.00	190.00
1	2	4	16	2	190.00	190.00
1	3	4	15	3	190.00	190.00
1	4	4	14	4	190.00	190.00
2	5	6	21	5	160.00	320.00
1	6	6	20	6	160.00	160.00
1	7	6	20	7	160.00	160.00
1	8	4	16	7	190.00	190.00
2	9	4	14	8	190.00	380.00
2	10	6	19	8	160.00	320.00
\.


--
-- Data for Name: imagenes_producto; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.imagenes_producto (id_imagen, id_producto, id_variante, orden, descripcion_alt, url_imagen) FROM stdin;
190	5	17	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/f69omg2p9lno2dbshio6.webp
191	5	17	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/sfstj5ol9hzkqftzjexv.webp
192	5	17	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/tfiz8x0ol4g4sd50nnms.webp
193	5	17	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950142/tvdyggnpxxg1efb4uvvo.webp
194	5	17	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950142/ouwcnfld1i0znx0cb31d.webp
195	5	18	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/f69omg2p9lno2dbshio6.webp
196	5	18	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/sfstj5ol9hzkqftzjexv.webp
197	5	18	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/tfiz8x0ol4g4sd50nnms.webp
198	5	18	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950142/tvdyggnpxxg1efb4uvvo.webp
199	5	18	0	Casaca Training Hombre Adidas D4t Full-zip - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950142/ouwcnfld1i0znx0cb31d.webp
224	4	16	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
225	4	16	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/uwkvcphk3nydeuuem4an.webp
226	4	16	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938615/cpq2anxetjiwk72gcebj.webp
227	4	16	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938617/oyixnphullivtyggwq5r.webp
228	4	15	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
229	4	15	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/uwkvcphk3nydeuuem4an.webp
230	4	15	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938615/cpq2anxetjiwk72gcebj.webp
231	4	15	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938617/oyixnphullivtyggwq5r.webp
232	4	14	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
233	4	14	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/uwkvcphk3nydeuuem4an.webp
234	4	14	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938615/cpq2anxetjiwk72gcebj.webp
235	4	14	0	Casaca Urbana Hombre Adidas Essentials Climawarm - Negro	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938617/oyixnphullivtyggwq5r.webp
178	6	19	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
179	6	19	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/o3zkef7bt9hx3ydrv8fv.webp
180	6	19	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/fdmeb8pap5ajb7aloqan.webp
181	6	19	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/ar4l4urcuursprolu8fn.webp
182	6	21	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
183	6	21	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/o3zkef7bt9hx3ydrv8fv.webp
184	6	21	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/fdmeb8pap5ajb7aloqan.webp
185	6	21	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/ar4l4urcuursprolu8fn.webp
186	6	20	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
187	6	20	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/o3zkef7bt9hx3ydrv8fv.webp
188	6	20	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/fdmeb8pap5ajb7aloqan.webp
189	6	20	0	Casaca Running Hombre Nike - Verde Oliva	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/ar4l4urcuursprolu8fn.webp
\.


--
-- Data for Name: marcas; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.marcas (id_marca, codigo_corto, descripcion, nombre) FROM stdin;
6	\N		CONVERSE
7	\N		ADIDAS
8	\N		NIKE
\.


--
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.movimientos (id_movimiento, comentario, comprobante, fecha, monto, tipo, id_cliente) FROM stdin;
1	ss	ss	2026-01-20 19:13:12.79835	200	DEUDA	1
2	ss	dd	2026-01-20 19:14:20.499447	150	PAGO	1
3	aa	aa	2026-01-20 19:14:31.800408	25	PAGO	1
4	df	ff	2026-01-20 19:14:42.800041	30	PAGO	1
5	ssf	fdfd	2026-01-20 19:14:52.501956	5	DEUDA	1
6	ssdsd	asdasd	2026-01-20 19:16:36.597739	50	DEUDA	2
7	aas	asdsd	2026-01-20 19:16:59.699375	90	DEUDA	1
8	aasssd	aaasss	2026-01-20 19:17:20.399802	200	DEUDA	4
9	123	122	2026-01-23 19:17:11.741502	50	DEUDA	15
\.


--
-- Data for Name: producto_variantes; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.producto_variantes (id_producto, id_variante, stock_actual, color, talla, sku_variante, url_imagen) FROM stdin;
4	15	7	Negro	M	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
5	17	15	Negro	M	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/f69omg2p9lno2dbshio6.webp
5	18	10	Negro	L	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950141/f69omg2p9lno2dbshio6.webp
6	21	0	Verde Oliva	L	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
4	14	7	Negro	S	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
6	19	8	Verde Oliva	S	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
4	16	11	Negro	L	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768938614/vvkno5onpbjobwsbioqn.webp
6	20	5	Verde Oliva	M	\N	https://res.cloudinary.com/drvogqn4x/image/upload/v1768950738/tpxqru3g4gxtqmqf8xpg.webp
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.productos (id_categoria, id_marca, id_producto, precio_compra, precio_regular, precio_venta, stock_actual, codigo_sku, descripcion, nombre, url_imagen, caracteristicas, en_oferta) FROM stdin;
14	7	5	50.00	300.00	230.00	25	CAS-ADI-002	Casaca Training Hombre Adidas D4t Full-zip	Casaca Training Hombre Adidas D4t Full-zip		{}	t
14	7	4	50.00	280.00	190.00	25	CAS-ADI-001	Casaca Urbana Hombre Adidas Essentials Climawarm	Casaca Urbana Hombre Adidas Essentials Climawarm		{}	f
14	8	6	80.00	\N	160.00	13	CAS-NIK-001	Casaca Running Hombre Nike	Casaca Running Hombre Nike		{}	f
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.usuarios (activo, id_usuario, fecha_creacion, celular, rol, nombre_usuario, apellidos, nombres, hash_contrasena, permisos) FROM stdin;
t	2	2025-12-15 22:18:24.253725	999999999	ADMIN	admin	Admin	Super	$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG	\N
t	3	\N	900944156	ADMIN	hugomeneses	Meneses Inca	Hugo Mishell	$2a$10$BNxzxkoLKrKnGik5TRiEXey54uW.Jy3.T29ldCyC6xd6tbXpnh23y	[]
t	7	\N	971726362	VENDEDOR	carlospro	Meneses Inca	Juan Carlos	$2a$10$FKGC/RRbDkUMRyfXbaL5he1B7OIjuomNpQmWEf4wpB2OKuJYaUeZu	[]
f	5	\N	989784785	VENDEDOR	maga	Maga Maga	Maga	$2a$10$v7C5wv1EtkQAc3djXf9VPOnH1rRh9p5H5mrNawM8vDb9wtdnos3wC	[]
t	8	\N	971442268	VENDEDOR	willdev07	Meneses	Percy	$2a$10$iRQoUrTs0MPrplrqGhSy.OH4Eh9AOoXfXAp4wf6OGBZyDcFdAqpwu	[]
t	4	\N	945641651	VENDEDOR	bubuchita	Alcala Peralta	Angie Nicole	$2a$10$51s5DrgtO0K2GCvuN5gI7Ov3uJ577cdLsbqxJ2m3iOhfHPsbL1UCC	[]
t	6	\N	948464131	MODERADOR	esmeralda	EsmeraldaEsmeralda	Esmeralda	$2a$10$nmhuKYs7iS8IWo91nDH0PuYbAcPSUmvBhZyoKqSxwO2657Oq1s3Yu	["GESTIONAR_CATEGORIAS", "VER_DASHBOARD"]
\.


--
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: margarita_db_v2_user
--

COPY public.ventas (id_cliente, id_cupom, id_usuario, id_venta, monto_descuento, total, fecha_venta, estado, tipo_comprobante) FROM stdin;
9	\N	4	1	0.00	190.00	2026-01-20 19:51:55.97131	ANULADA	boleta
15	\N	4	2	0.00	190.00	2026-01-20 21:00:45.243314	COMPLETADA	boleta
17	\N	4	3	0.00	190.00	2026-01-20 21:17:41.044125	COMPLETADA	boleta
18	\N	4	4	0.00	190.00	2026-01-20 22:13:38.560035	COMPLETADA	boleta
9	\N	4	5	0.00	320.00	2026-01-20 23:13:36.358056	COMPLETADA	boleta
9	\N	4	8	0.00	700.00	2026-01-24 01:06:40.369908	COMPLETADA	boleta
9	\N	4	7	0.00	350.00	2026-01-23 21:11:05.806557	ANULADA	boleta
9	\N	4	6	0.00	160.00	2026-01-20 23:15:01.555377	ANULADA	boleta
\.


--
-- Name: cajas_id_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.cajas_id_caja_seq', 1, false);


--
-- Name: categorias_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.categorias_id_categoria_seq', 14, true);


--
-- Name: clientes_id_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.clientes_id_cliente_seq', 19, true);


--
-- Name: cupones_id_cupom_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.cupones_id_cupom_seq', 2, true);


--
-- Name: detalle_venta_id_detalle_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.detalle_venta_id_detalle_seq', 10, true);


--
-- Name: imagenes_producto_id_imagen_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.imagenes_producto_id_imagen_seq', 235, true);


--
-- Name: marcas_id_marca_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.marcas_id_marca_seq', 8, true);


--
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.movimientos_id_movimiento_seq', 9, true);


--
-- Name: producto_variantes_id_variante_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.producto_variantes_id_variante_seq', 21, true);


--
-- Name: productos_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.productos_id_producto_seq', 6, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 8, true);


--
-- Name: ventas_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: margarita_db_v2_user
--

SELECT pg_catalog.setval('public.ventas_id_venta_seq', 8, true);


--
-- Name: cajas cajas_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.cajas
    ADD CONSTRAINT cajas_pkey PRIMARY KEY (id_caja);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria);


--
-- Name: clientes clientes_dni_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_dni_key UNIQUE (dni);


--
-- Name: clientes clientes_email_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_email_key UNIQUE (email);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente);


--
-- Name: cupones cupones_codigo_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT cupones_codigo_key UNIQUE (codigo);


--
-- Name: cupones cupones_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT cupones_pkey PRIMARY KEY (id_cupom);


--
-- Name: detalle_venta detalle_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT detalle_venta_pkey PRIMARY KEY (id_detalle);


--
-- Name: imagenes_producto imagenes_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT imagenes_producto_pkey PRIMARY KEY (id_imagen);


--
-- Name: marcas marcas_nombre_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_nombre_key UNIQUE (nombre);


--
-- Name: marcas marcas_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_pkey PRIMARY KEY (id_marca);


--
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id_movimiento);


--
-- Name: producto_variantes producto_variantes_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.producto_variantes
    ADD CONSTRAINT producto_variantes_pkey PRIMARY KEY (id_variante);


--
-- Name: productos productos_codigo_sku_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_codigo_sku_key UNIQUE (codigo_sku);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id_producto);


--
-- Name: usuarios usuarios_nombre_usuario_key; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_nombre_usuario_key UNIQUE (nombre_usuario);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id_venta);


--
-- Name: detalle_venta fk2ens3kcdecgap5og51rbsp1h0; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fk2ens3kcdecgap5og51rbsp1h0 FOREIGN KEY (id_variante) REFERENCES public.producto_variantes(id_variante);


--
-- Name: imagenes_producto fk9bgwqaobnsa1muydxwo18en5r; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT fk9bgwqaobnsa1muydxwo18en5r FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: ventas fk9mbivrllsn9jffa05x77l5mc1; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk9mbivrllsn9jffa05x77l5mc1 FOREIGN KEY (id_cupom) REFERENCES public.cupones(id_cupom);


--
-- Name: categorias fkbt5pdc52jh54l2o97ic983j26; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT fkbt5pdc52jh54l2o97ic983j26 FOREIGN KEY (id_categoria_padre) REFERENCES public.categorias(id_categoria);


--
-- Name: productos fkc1mrc7r89nch4xtol227kdwce; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkc1mrc7r89nch4xtol227kdwce FOREIGN KEY (id_marca) REFERENCES public.marcas(id_marca);


--
-- Name: productos fkdtoa37luoxhhvbicrfiu5ygbj; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkdtoa37luoxhhvbicrfiu5ygbj FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria);


--
-- Name: detalle_venta fke92fd2auy9ms2pvac9b4n8ttq; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fke92fd2auy9ms2pvac9b4n8ttq FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: detalle_venta fkgds50vmwbs8lxoti80iekstyi; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fkgds50vmwbs8lxoti80iekstyi FOREIGN KEY (id_venta) REFERENCES public.ventas(id_venta);


--
-- Name: movimientos fkggso8fbp0cpimqjskv15qu917; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fkggso8fbp0cpimqjskv15qu917 FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente);


--
-- Name: cajas fkkal46lhycb4457wk2b7r9gb80; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.cajas
    ADD CONSTRAINT fkkal46lhycb4457wk2b7r9gb80 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: ventas fkleerof1mym3gc1ah8hsarel3f; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkleerof1mym3gc1ah8hsarel3f FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente);


--
-- Name: imagenes_producto fkmlw1jk3iwkgb04aea290rp09x; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.imagenes_producto
    ADD CONSTRAINT fkmlw1jk3iwkgb04aea290rp09x FOREIGN KEY (id_variante) REFERENCES public.producto_variantes(id_variante);


--
-- Name: ventas fkngvsjlvvv240ohesoj9e87s3h; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkngvsjlvvv240ohesoj9e87s3h FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: producto_variantes fkq7ega29yp2m3irjvvrfrwsq6i; Type: FK CONSTRAINT; Schema: public; Owner: margarita_db_v2_user
--

ALTER TABLE ONLY public.producto_variantes
    ADD CONSTRAINT fkq7ega29yp2m3irjvvrfrwsq6i FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: margarita_db_v2_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO margarita_db_v2_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO margarita_db_v2_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO margarita_db_v2_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO margarita_db_v2_user;


--
-- PostgreSQL database dump complete
--

\unrestrict lZEOxUGJJXU2fUDJJrZlS5UggAwJIvCt82heAydaeydDUfDJNOgC3gRewABTpYz

